name: AssetDuJour
id: assetdujour
version: 1.1
author_link: http://ubiquitic.com/
author_name: François Nonnenmacher, Ubiquitic
plugin_link: http://ubiquitic.com/software/assetdujour-movable-type-plugin.html
description: <__trans phrase="Preselects the date “du jour” in the asset upload form.">
l10n_class: AssetDuJour::L10N

callbacks:
    MT::App::CMS::template_source.asset_upload: AssetDuJour::Plugin::xfm
